export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL;
export const SOCKET_BASE_URL = process.env.NEXT_PUBLIC_SOCKET_URL;
export const CLOUDINARY_UPLOAD_PRESET = process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET;
export const CLOUDINARY_CLOUD_NAME = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;